// <auto-generated />
using System.Collections.Generic;
using Dota2Analytics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dota2Analytics.Data.Migrations
{
    [DbContext(typeof(DotaContext))]
    [Migration("20250811120116_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("integer");

                    b.Property<int>("AgilityIncrease")
                        .HasColumnType("integer");

                    b.Property<int>("Armor")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Aspect")
                        .HasColumnType("integer[]");

                    b.Property<int>("AttackInterval")
                        .HasColumnType("integer");

                    b.Property<int>("AttackRange")
                        .HasColumnType("integer");

                    b.Property<int>("AttackSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("AttackType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Damage")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InnateAbility")
                        .HasColumnType("text");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<int>("IntelligenceIncrease")
                        .HasColumnType("integer");

                    b.Property<int>("Mana")
                        .HasColumnType("integer");

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("StrengthIncrease")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.Property<string>("TalantTree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.HeroStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AverageGpm")
                        .HasColumnType("integer");

                    b.Property<int>("AverageXpm")
                        .HasColumnType("integer");

                    b.Property<int>("BestWintstrick")
                        .HasColumnType("integer");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<int>("WinRate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeroId")
                        .IsUnique();

                    b.ToTable("HeroStats");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Iteam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActiveDescription")
                        .HasColumnType("text");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Effects")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ManaCost")
                        .HasColumnType("integer");

                    b.Property<int?>("MatchPlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RecipeCost")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int?>("Сooldown")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerId");

                    b.ToTable("Iteams");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DierScore")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RadiantScore")
                        .HasColumnType("integer");

                    b.Property<string>("SteamMatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WinnerTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.MatchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assists")
                        .HasColumnType("integer");

                    b.Property<int?>("BountyRunes")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingDamage")
                        .HasColumnType("integer");

                    b.Property<int?>("CampsStacked")
                        .HasColumnType("integer");

                    b.Property<int?>("CreepsDenies")
                        .HasColumnType("integer");

                    b.Property<int?>("CreepsLastHit")
                        .HasColumnType("integer");

                    b.Property<int?>("DamageRecivedRaw")
                        .HasColumnType("integer");

                    b.Property<int?>("DamageRecivedReduced")
                        .HasColumnType("integer");

                    b.Property<int?>("Deth")
                        .HasColumnType("integer");

                    b.Property<int>("Gpm")
                        .HasColumnType("integer");

                    b.Property<int?>("Heal")
                        .HasColumnType("integer");

                    b.Property<int?>("HeroDamage")
                        .HasColumnType("integer");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<int?>("Kills")
                        .HasColumnType("integer");

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("NetWorth")
                        .HasColumnType("integer");

                    b.Property<int?>("OutpostCaptured")
                        .HasColumnType("integer");

                    b.Property<int>("Pick")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerLevel")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("SupportContribution")
                        .HasColumnType("text[]");

                    b.Property<int?>("SupportGoldSpent")
                        .HasColumnType("integer");

                    b.Property<int>("Xpm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeroId")
                        .IsUnique();

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MatchEventId")
                        .HasColumnType("integer");

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int?>("MathId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int?>("SteamAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("WinRate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchEventId");

                    b.HasIndex("MatchId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Affects")
                        .HasColumnType("text");

                    b.Property<string>("DamageType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Dispellable")
                        .HasColumnType("boolean");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<int?>("ManaCost")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("PiercesDebuffImmunity")
                        .HasColumnType("boolean");

                    b.Property<int?>("Range")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int?>("Сooldown")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Hero", b =>
                {
                    b.HasOne("Dota2Analytics.Data.Entities.Match", null)
                        .WithMany("Heroes")
                        .HasForeignKey("MatchId");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.HeroStats", b =>
                {
                    b.HasOne("Dota2Analytics.Data.Entities.Hero", "Hero")
                        .WithOne("HeroStats")
                        .HasForeignKey("Dota2Analytics.Data.Entities.HeroStats", "HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Iteam", b =>
                {
                    b.HasOne("Dota2Analytics.Data.Entities.MatchPlayer", "MatchPlayer")
                        .WithMany("Iteams")
                        .HasForeignKey("MatchPlayerId");

                    b.Navigation("MatchPlayer");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.MatchEvent", b =>
                {
                    b.HasOne("Dota2Analytics.Data.Entities.Match", "Match")
                        .WithMany("MatchEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.MatchPlayer", b =>
                {
                    b.HasOne("Dota2Analytics.Data.Entities.Hero", "Hero")
                        .WithOne("MatchPlayer")
                        .HasForeignKey("Dota2Analytics.Data.Entities.MatchPlayer", "HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dota2Analytics.Data.Entities.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchId");

                    b.HasOne("Dota2Analytics.Data.Entities.Player", "Player")
                        .WithOne("MatchPlayer")
                        .HasForeignKey("Dota2Analytics.Data.Entities.MatchPlayer", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Player", b =>
                {
                    b.HasOne("Dota2Analytics.Data.Entities.MatchEvent", "MatchEvent")
                        .WithMany("Players")
                        .HasForeignKey("MatchEventId");

                    b.HasOne("Dota2Analytics.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId");

                    b.Navigation("Match");

                    b.Navigation("MatchEvent");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Skill", b =>
                {
                    b.HasOne("Dota2Analytics.Data.Entities.Hero", "Hero")
                        .WithMany("Skills")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Hero", b =>
                {
                    b.Navigation("HeroStats")
                        .IsRequired();

                    b.Navigation("MatchPlayer")
                        .IsRequired();

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Match", b =>
                {
                    b.Navigation("Heroes");

                    b.Navigation("MatchEvents");

                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.MatchEvent", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.MatchPlayer", b =>
                {
                    b.Navigation("Iteams");
                });

            modelBuilder.Entity("Dota2Analytics.Data.Entities.Player", b =>
                {
                    b.Navigation("MatchPlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
